import test from 'node:test';
import assert from 'node:assert/strict';
import {clientSecretIssue,configuredSecrets,unsafePublicName} from '../scripts/client-secrets.mjs';
import {fullPolicy,inlineScriptHashes as nodeHashes} from '../scripts/security-policy.mjs';
import {contentSecurityPolicy,inlineScriptHashes} from '../src/server/securityHeaders';
// Deliberately fictional tokens: ensure security tooling never returns their values.
const privateValue='private-sentinel-value-for-stage2';
test('production configuration accepts intended Supabase anon and RevenueCat Apple public keys',async()=>{const anon=Buffer.from(JSON.stringify({role:'anon'})).toString('base64url');const key=`eyJhbGciOiJIUzI1NiJ9.${anon}.fictionalsignature`;const values=await configuredSecrets({NEXT_PUBLIC_SUPABASE_ANON_KEY:key,NEXT_PUBLIC_REVENUECAT_IOS_API_KEY:'appl_public-example-for-test',SUPABASE_SERVICE_ROLE_KEY:privateValue},[]);assert.deepEqual(values,[privateValue]);assert.equal(clientSecretIssue(key+' appl_public-example-for-test',values),null);assert.equal(unsafePublicName('NEXT_PUBLIC_SUPABASE_ANON_KEY NEXT_PUBLIC_REVENUECAT_IOS_API_KEY'),false);});
test('checker detects configured secret leakage including shell-injected configuration',async()=>{const values=await configuredSecrets({SMILE_GEMINI_API_KEY:privateValue},[]);const issue=clientSecretIssue(`const leaked="${privateValue}";`,values);assert.equal(issue,'configured private secret');assert.ok(!issue?.includes(privateValue));});
test('safe public variable names do not excuse a service-role JWT or secret value',()=>{const payload=Buffer.from(JSON.stringify({role:'service_role',x:1})).toString('base64url');assert.equal(clientSecretIssue(`NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiJ9.${payload}.signature"`),'Supabase service-role JWT');assert.equal(clientSecretIssue('NEXT_PUBLIC_REVENUECAT_IOS_API_KEY="sk_live_12345678901234567890"'),'private API key');assert.equal(unsafePublicName('NEXT_PUBLIC_GEMINI_API_KEY'),true);});
test('checker catches unconfigured private credentials and PEM material',()=>{for(const value of ['AIza'+'a'.repeat(35),'sk-proj-'+'a'.repeat(36),'sb_secret_'+'a'.repeat(24),'-----BEGIN PRIVATE KEY-----','SUPABASE_SERVICE_ROLE_KEY'])assert.ok(clientSecretIssue(value),value.slice(0,8));});
test('CSP hashes exact inline appearance/bootstrap scripts and disallows inline event handlers',async()=>{const html='<script>appearance()</script><script src="/app.js"></script><script>boot()</script>';const hashes=await inlineScriptHashes(html);assert.deepEqual(hashes,nodeHashes(html));assert.equal(hashes.length,2);const policy=contentSecurityPolicy('https://project.supabase.co',hashes);for(const hash of hashes)assert.ok(policy.includes(`'${hash}'`));assert.match(policy,/script-src 'self' 'wasm-unsafe-eval'/);assert.match(policy,/script-src-attr 'none'/);assert.match(policy,/worker-src 'self'/);assert.doesNotMatch(policy,/script-src[^;]*'unsafe-(?:inline|eval)'/);});
test('web/native CSP allows local CPU WASM while external model CDNs and telemetry stay blocked',()=>{const web=contentSecurityPolicy('https://project.supabase.co'),native=fullPolicy([],{supabaseOrigin:'https://project.supabase.co',apiOrigin:'https://smile.test',native:true});for(const policy of [web,native]){assert.match(policy,/connect-src 'self' data: blob:/);assert.doesNotMatch(policy,/cdn.jsdelivr|storage.googleapis|odml.pa|script-src[^;]*https:/);}assert.ok(native.includes('https://smile.test'));assert.ok(!native.includes('upgrade-insecure-requests'));});
import {extractHeicWorker} from '../scripts/heic-worker.mjs';
import {readFileSync} from 'node:fs';
import {z} from '../src/lib/zod';
test('client schemas use interpreted validation without a Function capability probe',()=>{assert.equal(z.config().jitless,true);assert.equal(z.object({name:z.string().min(1)}).safeParse({name:'case'}).success,true);assert.equal(z.object({name:z.string().min(1)}).safeParse({name:''}).success,false);});
test('HEIC CSP decoder is served as a valid local worker and unexpected dependency packaging blocks the build',()=>{const worker=extractHeicWorker(readFileSync('node_modules/heic-to/dist/csp/heic-to.js','utf8'));assert.ok(worker.includes('HeifDecoder'));assert.ok(worker.includes('onmessage='));assert.throws(()=>extractHeicWorker('export const changed=true;'),/packaging changed/);});
