import test from 'node:test';
import assert from 'node:assert/strict';
import {createInferenceWorker,type WorkerPort} from '../src/lib/vision/workerClient';
import {createRefinementCache,needsRefinement} from '../src/lib/toothMap/refinementPolicy';
import {activateWorkspace,captureWorkspace} from '../src/lib/workspace';
import type {ToothMap} from '../src/lib/toothMap/types';
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
function fixture(timeout=1000){const ports:{port:WorkerPort;messages:{id:number;payload:unknown}[];closed:boolean}[]=[];const rpc=createInferenceWorker(()=>{const record={port:null as unknown as WorkerPort,messages:[] as {id:number;payload:unknown}[],closed:false};record.port={onmessage:null,onerror:null,postMessage(message){record.messages.push(message as {id:number;payload:unknown});},terminate(){record.closed=true;}};ports.push(record);return record.port;},timeout);return {ports,rpc,respond(index:number,value:unknown){const r=ports[index],id=r.messages.at(-1)!.id;r.port.onmessage?.({data:{id,result:value}} as MessageEvent);}};}
const map={method:'on-device-v1',confirmedByClinician:false} as ToothMap;
test('ordinary Studio preset does not invoke SlimSAM',()=>assert.equal(needsRefinement(map,{single:false,custom:false,review:false}),false));
test('Custom and Review invoke refinement when required',()=>{assert.equal(needsRefinement(map,{single:false,custom:true,review:false}),true);assert.equal(needsRefinement(map,{single:false,custom:false,review:true}),true);});
test('single-tooth invokes refinement only for an unreviewed classical map',()=>{assert.equal(needsRefinement(map,{single:true,custom:false,review:false}),true);for(const current of [{...map,confirmedByClinician:true},{...map,method:'on-device-sam' as const},{...map,method:'manual' as const},null])assert.equal(needsRefinement(current,{single:true,custom:true,review:true}),false);});
test('refinement cache reuses valid results, limits memory and clears on detach',()=>{const cache=createRefinementCache<object>(2),value={photo:'a'};cache.set('a',value);assert.equal(cache.get('a'),value);cache.set('b',{});cache.get('a');cache.set('c',{});assert.equal(cache.get('b'),undefined);cache.clear();assert.equal(cache.get('a'),undefined);});
test('worker sessions are reused between requests and queued work runs serially',async()=>{const f=fixture(),a=f.rpc.request<number>({a:1}),b=f.rpc.request<number>({b:2});await tick();assert.equal(f.ports.length,1);assert.equal(f.ports[0].messages.length,1);f.respond(0,11);assert.equal(await a,11);await tick();assert.equal(f.ports[0].messages.length,2);f.respond(0,22);assert.equal(await b,22);f.rpc.reset();});
test('wrong request IDs and late terminated worker results are ignored',async()=>{const f=fixture(),abort=new AbortController(),old=f.rpc.request({},abort.signal);const rejected=assert.rejects(old,/cancelled/);await tick();const stale=f.ports[0].port.onmessage;abort.abort();await rejected;const next=f.rpc.request<string>({next:true});await tick();stale?.({data:{id:1,result:'stale'}} as MessageEvent);f.ports[1].port.onmessage?.({data:{id:999,result:'wrong'}} as MessageEvent);f.respond(1,'current');assert.equal(await next,'current');assert.equal(f.ports[0].closed,true);f.rpc.reset();});
test('inference errors reject safely and permit a later request',async()=>{const f=fixture(),a=f.rpc.request({});const rejected=assert.rejects(a,/unavailable/);await tick();f.ports[0].port.onmessage?.({data:{id:1,error:true}} as MessageEvent);await rejected;const b=f.rpc.request<number>({});await tick();f.respond(0,3);assert.equal(await b,3);f.rpc.reset();});
test('worker crashes recreate the runtime; aborted queued jobs never receive patient data',async()=>{const f=fixture(),cancel=new AbortController(),a=f.rpc.request({}),b=f.rpc.request({},cancel.signal);const rejectedA=assert.rejects(a,/unavailable/),rejectedB=assert.rejects(b);await tick();cancel.abort();f.ports[0].port.onerror?.({} as ErrorEvent);await rejectedA;await rejectedB;assert.equal(f.ports.length,1);assert.equal(f.ports[0].messages.length,1);});
test('timeout releases worker memory and reports an analysis failure',async()=>{const f=fixture(10);await assert.rejects(f.rpc.request({}),/timed out/);assert.equal(f.ports[0].closed,true);});
test('switching account aborts in-flight inference and invalidates the captured lease',async()=>{activateWorkspace({kind:'account',userId:'vision-a'});const lease=captureWorkspace(),f=fixture(),a=f.rpc.request({},lease.signal),rejected=assert.rejects(a,/cancelled/);await tick();activateWorkspace({kind:'account',userId:'vision-b'});await rejected;assert.throws(()=>lease.assert(),/account changed/);assert.equal(f.ports[0].closed,true);activateWorkspace({kind:'unowned'});});
